version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/energydb
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3001:80"  # Cambia a 80 si usas nginx
    depends_on:
      - backend

volumes:
  mongodb:
